In [4]:
a=10
b=20
c=a+b
print(c)


30


a= 10
a

In [5]:
a=10
print(a)

10


In [6]:
help('keywords')


Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 



In [9]:
from keyword import kwlist
kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [ ]:
#identifier
#keyword
#operators
# 1. arithmetic:+,-,*,/,**,//,%
# 2.relational: ==,!=,>,<,>=,<=
# 3.Assignment: =,+=,-=,*=......
# 4.Logical: and,or,not
# 5.Membership:in ,not in
# 6 Bitwise: &,|,%,~,<<,>>
# 7.Identity: is,is not 
# Data types/Data classes
#Numeric : int,float,complex
#Sequences:
# str:immutabl ecollection of characters '' ,"",''' '''ArithmeticError
#[] list: mutable and unstructured coll of het elements
#() Tuple: immutable and unstructured coll of het elements
#Mapping:
# {} dict: mutable and structured coll of key value pairs
#Set:
#{}  set: unorderd collection of unique items
# Boolean:
# bool: True False(anything non zero and non empty is true)
#Empty data:
#NoneType: None
# Data operations(Collections)
# 1.Item accessing(indexing/slicing/subscriotion)
#2,Item insertion
# 3.Item assignment(possible  with mutable only)
#4.Item deletion(possible with mutable only)
#Data type Built-in Functuons
#str: upper,lower,find ,split,sprit,joint,format,count
# list: append ,sort,clear,copy,insert,remove,Index,pop
# Tuple: cont ,Index 
# dict:  keys,values,update,pop
# set: add,difference,union,pop,remove

In [28]:
a=34
b=34.5
c=34+5j
d='hello'
e=[3,4,5]
f=(3,4,5)
g={3:[4,5]}
h={3,4,5}

In [13]:
e.append('45')
e

[3, 4, 5, '45']

In [18]:
e.sort()
e

[3, 4, 5, 1000, 1000]

In [17]:
e.insert(2,1000)
e

[3, 4, 1000, 1000, 5]

In [19]:
e1=['hi','wow','good','yes']

In [1]:
e1.sort()
e1

NameError: name 'e1' is not defined

In [21]:
len(e1[0])

4

In [22]:
e.sort(reverse=True)
e

[1000, 1000, 5, 4, 3]

In [23]:
e1.sort(key=len,reverse =True)
e1

['good', 'wow', 'yes', 'hi']

In [24]:
k=e.pop()
k

3

In [25]:
g.keys()
g

{3: [4, 5]}

In [26]:
type(g.keys())

dict_keys

In [ ]:
'-'.join('wars')
'#'.join('hi thi sis a new stirng'.split() )
'hi this is a new string'.replace(' ','#') 


In [35]:
e3=e
e3

[3, 4, 5]

In [37]:
e4=e.copy()
e4.append(8)

In [38]:
e4

[3, 4, 5, 8]

In [33]:
g.get('z','Oh No')

'Oh No'

In [9]:
#string formatting
x=20
y=30
#z=ek aisa data jo 20 to 30 hai

#format specifier - deprecated
z='ek aisa data jo %d to %d hai' %(x,y)
#using format function
z='ek aisa data jo {} to {} hai'
z=z.format(x,y)
z
z1='ek aisa data jo {0} to {1} hai lekiin {0} hi kaafi hai'
z1
#using fstring
f'anything'
zf=f'ek aisa data jo {x}to {y} hai lekin {x} hi kafi hai'
zf

'ek aisa data jo 20to 30 hai lekin 20 hi kafi hai'

In [53]:
c.real

34.0

In [54]:
c.float

AttributeError: 'complex' object has no attribute 'float'

In [55]:
d.upper()

'HELLO'

In [56]:
d

'hello'

In [1]:
d.find('o')

NameError: name 'd' is not defined

In [2]:
d.split('e')

NameError: name 'd' is not defined

In [11]:
s='My name is nandani'
s[0]

'M'

In [12]:
s

'My name is nandani'

In [13]:
len(s)

18

In [15]:
s[3:7:1]

'name'

In [16]:
s[:7]

'My name'

In [17]:
s[-9:]

's nandani'

In [18]:
s[-11:-17:-1]

' eman '

In [19]:
s[-3:-7:-1]

'adna'

In [20]:
s[-9:-15:-1]

'si ema'

In [21]:
s[::-1]

'inadnan si eman yM'

In [23]:
s[-3:-7:-1]

'adna'

In [25]:
s[-8:-11:-1]

' si'

In [26]:
d={'a':34,'b':45,'c':[3,4,5,6,7]}

In [27]:
d['c'][2]

5

In [29]:
d1=[{'a':34},66,{'66':[{'00':[98,'hi']},'awesome',{'m':'n'}]}]

In [2]:
s='468hi3.4'
a=[4,6,8,'hi',3.4]
b=(4,6,8,'hi',3.4)
c={4:6,8:['hi',3.4]}
d={4,6,8,'hi',3.4}


In [3]:
type(s),type(a),type(b),type(c),type(d),

(str, list, tuple, dict, set)

In [4]:
len(s),len(a),len(b),len(c),len(d)

(8, 5, 5, 2, 5)

In [46]:
#item assignment
#s[0]='A'(not possible)
#a[0]='A'(done)
#b[0]='A'(not possible)
c[4]=66
c
# #item deletion
# del s[0](not possible)
#del a[0] (done)
# del b[0](not possible)
# del c[0] (done)

In [5]:
'hi'+'hello'

'hihello'

In [6]:
{3,4}+{4,6}

TypeError: unsupported operand type(s) for +: 'set' and 'set'

In [7]:
[4,5]+[3,6]

[4, 5, 3, 6]

In [8]:
(4,5)+(3,6)

(4, 5, 3, 6)

In [9]:
'hi'*3

'hihihi'

In [10]:
s+='k'
s

'468hi3.4k'

In [11]:
s[:3]

'468'

In [12]:
s[3:]

'hi3.4k'

In [16]:
s=s[:3]+'job'+s[3:]
s

'468jobjobhi3.4k'

In [17]:
a

[4, 6, 8, 'hi', 3.4]

In [20]:
a+=['bye']
a

[4, 6, 8, 'hi', 3.4, 'bye']

In [21]:
a=a[:2]+[39]+a[2:]
a

[4, 6, 39, 8, 'hi', 3.4, 'bye']

In [24]:
b+=('bye',)
b

(4, 6, 8, 'hi', 3.4, 'bye')

In [25]:
(3+4)*9

63

In [26]:
(3+4,)*9

(7, 7, 7, 7, 7, 7, 7, 7, 7)

In [27]:
(*b,*b)

(4, 6, 8, 'hi', 3.4, 'bye', 4, 6, 8, 'hi', 3.4, 'bye')

In [28]:
(*b,*c,*a)

(4, 6, 8, 'hi', 3.4, 'bye', 4, 8, 4, 6, 39, 8, 'hi', 3.4, 'bye')

In [29]:
a+b

TypeError: can only concatenate list (not "tuple") to list

In [31]:
(*a,*b,*s)

(4,
 6,
 39,
 8,
 'hi',
 3.4,
 'bye',
 4,
 6,
 8,
 'hi',
 3.4,
 'bye',
 '4',
 '6',
 '8',
 'j',
 'o',
 'b',
 'j',
 'o',
 'b',
 'h',
 'i',
 '3',
 '.',
 '4',
 'k')

In [32]:
*a,*b,*s

(4,
 6,
 39,
 8,
 'hi',
 3.4,
 'bye',
 4,
 6,
 8,
 'hi',
 3.4,
 'bye',
 '4',
 '6',
 '8',
 'j',
 'o',
 'b',
 'j',
 'o',
 'b',
 'h',
 'i',
 '3',
 '.',
 '4',
 'k')

In [33]:
c[4]

6

In [34]:
c['type']='ekValue'

In [35]:
c[99]=[86,'ekValue']
c

{4: 6, 8: ['hi', 3.4], 'type': 'ekValue', 99: [86, 'ekValue']}

In [36]:
c2={'a':45,'b':35}
print(c)
print(c2)

{4: 6, 8: ['hi', 3.4], 'type': 'ekValue', 99: [86, 'ekValue']}
{'a': 45, 'b': 35}


In [37]:
{**c,**c2}

{4: 6,
 8: ['hi', 3.4],
 'type': 'ekValue',
 99: [86, 'ekValue'],
 'a': 45,
 'b': 35}

In [ ]:
#(*args,**kwargs)

In [51]:
print(bool(' '),bool([]),bool({}),bool(()),bool(-1),bool([()]))

True False False False True True


In [39]:
a=10
if(a>5):
    print("or ye to bada hai")
    if(a<100):
        print("ye bhi thik hi hai")
        print("ye ho gaya")
    elif(a< -20):
        print("ye bhut chhota hai")
    elif(a==3):
        print("ye vala 3 hai")
    else:
        print("ye theek hai")
        print("sb khatm")

or ye to bada hai
ye bhi thik hi hai
ye ho gaya


In [ ]:
#conditional statement
#if-elif-else 
#looping
#while-else ,for-else ,continue/break
#error handling

#classes
#class

In [40]:
a=20
while a>0:
    print('hello',a)
    a-=3
    if(a==11):
        break
    if(a<10):
        continue
    print('one more')


hello 20
one more
hello 17
one more
hello 14


In [41]:
for i in range(1,11):
    print (i,'*')

1 *
2 *
3 *
4 *
5 *
6 *
7 *
8 *
9 *
10 *


In [ ]:
!python -m pip install numpy

In [1]:
import numpy as py


In [2]:
import numpy as np

In [6]:
a=np.array([8,6,5])
a

array([8, 6, 5])

In [9]:
b=np.array([[[4,41],[8,81],[7,71]],[[3,31],[1,11],[5,51]],[[6,61],[9,91],[13,131]]])
b

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [10]:
b.shape

(3, 3, 2)

In [12]:
b[0,:]

array([[ 4, 41],
       [ 8, 81],
       [ 7, 71]])

In [11]:
b[1,:]

array([[ 3, 31],
       [ 1, 11],
       [ 5, 51]])

In [14]:
b[0:5:1]

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [15]:
b[2:3]

array([[[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [18]:
b[:,-1,:]

array([[  7,  71],
       [  5,  51],
       [ 13, 131]])

In [21]:
b[1:3:1,1:3:1,0]

array([[ 1,  5],
       [ 9, 13]])

In [22]:
b+5

array([[[  9,  46],
        [ 13,  86],
        [ 12,  76]],

       [[  8,  36],
        [  6,  16],
        [ 10,  56]],

       [[ 11,  66],
        [ 14,  96],
        [ 18, 136]]])

In [3]:
import numpy as np

In [6]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [12]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
list(range(1,11,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [13]:
np.random.randint(1,6,1)

array([5])

In [14]:
np.random.randint(1,6,[4,3,2])

array([[[4, 5],
        [5, 4],
        [4, 2]],

       [[1, 3],
        [3, 4],
        [4, 3]],

       [[2, 2],
        [3, 1],
        [2, 3]],

       [[1, 1],
        [4, 3],
        [3, 2]]])

In [15]:
np.random.randint(31,6000,[4,3])

array([[1860, 5766, 1093],
       [4160, 5643, 3358],
       [1953, 1454, 2990],
       [3412, 2193, 2623]])

In [16]:
np.random.seed(10)

In [17]:
np.random.seed(10)
np.random.randint(31,6000,[4,3])

array([[1320, 4654, 1375],
       [3472, 1211, 2040],
       [4860, 1551, 1980],
       [2073, 1063, 1128]])

In [18]:
np.random.rand(3,4)

array([[0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607],
       [0.72175532, 0.29187607, 0.91777412, 0.71457578]])

In [24]:
r=np.loadtxt('somedata.txt',dtype=str)
r

array(['I', 'am', 'happy.'], dtype='<U6')

In [27]:
r=np.loadtxt('moredata.txt')
r

C:\Users\DELL\AppData\Local\Temp\ipykernel_6580\4276986145.py:1: UserWarning: loadtxt: input contained no data: "moredata.txt"
  r=np.loadtxt('moredata.txt')


array([], dtype=float64)

In [30]:
p=np.random.rand(3,4)

In [31]:
np.savetxt('new.txt',p,delimiter=',')